### ISSUE TITLE
Dialog displays the password

### ISSUE THREAD

**Issue by magicgoose** [nelenkov/cryptfs-password-manager#10]
After the password change, the app displays the password in a dialog. It defeats the purpose of using "hidden" `EditText`s for typing the password, because later it's fully visible on screen, making it dangerous to use in "crowded" environment. :P

It should be at least like "click *this button* if you want to see the password [again]".

**Comment by nelenkov** [comment]
This is by design. It gives you a last chance to see the actual password (which you might have mistyped). If you forget it or remember the wrong password, you will have to reset your device in order to use it. You certainly shouldn't be using this app in a crowded environment (Cf. shoulder surfing).
